// Dummy Data for ShopZone React App

// ─── HELPERS ────────────────────────────────────────────────────

export const fmt = (value) => {
  if (typeof value !== 'number') return value;
  return value.toLocaleString('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 });
};

export const discount = (price, comparePrice) => {
  const p = Number(price);
  const c = Number(comparePrice);
  if (!Number.isFinite(p) || !Number.isFinite(c) || c <= 0 || p >= c) return 0;
  return Math.round(((c - p) / c) * 100);
};

// ─── CATEGORIES ──────────────────────────────────────────────────

export const CATEGORIES = [
  { _id: 'Electronics', name: 'Electronics', icon: '💻' },
  { _id: 'Fashion', name: 'Fashion', icon: '👗' },
  { _id: 'Home & Kitchen', name: 'Home & Kitchen', icon: '🏠' },
  { _id: 'Beauty', name: 'Beauty', icon: '💄' },
  { _id: 'Books', name: 'Books', icon: '📚' },
  { _id: 'Sports', name: 'Sports', icon: '⚽' },
  { _id: 'Toys', name: 'Toys', icon: '🧸' },
  { _id: 'Groceries', name: 'Groceries', icon: '🛒' },
  { _id: 'Gaming', name: 'Gaming', icon: '🎮' },
];

// ─── PRODUCTS ────────────────────────────────────────────────────

export const PRODUCTS = [
  {
    _id: '1',
    name: 'Sony WH-1000XM5 Wireless Noise Cancelling Headphones',
    brand: 'Sony',
    category: 'Electronics',
    price: 18990,
    comparePrice: 32990,
    rating: 4.8,
    reviews: 2847,
    stock: 45,
    vendor: 'Sony India',
    description: 'Industry-leading noise cancellation with Dual Noise Sensor technology. Up to 30-hour battery life with quick charging. Touch sensor controls to pause/play/skip tracks, control volume, activate your voice assistant, and answer phone calls.',
    highlights: ['Industry-leading ANC', '30-hour battery life', 'Touch controls', 'Quick charge', 'Multipoint connection'],
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '2',
    name: 'Apple Watch Series 9 GPS 41mm Starlight Aluminum',
    brand: 'Apple',
    category: 'Electronics',
    price: 34900,
    comparePrice: 41900,
    rating: 4.9,
    reviews: 5123,
    stock: 23,
    vendor: 'Apple India',
    description: 'The most advanced Apple Watch ever. Featuring the S9 SiP with a powerful Neural Engine, a super-bright display, and Double Tap for magical new ways to interact.',
    highlights: ['S9 SiP chip', 'Double Tap gesture', 'Always-On Retina display', 'Water resistant 50m', 'GPS + Cellular options'],
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '3',
    name: 'Apple MacBook Air M2 13-inch 8GB RAM 256GB SSD',
    brand: 'Apple',
    category: 'Electronics',
    price: 89990,
    comparePrice: 114900,
    rating: 4.9,
    reviews: 7891,
    stock: 12,
    vendor: 'Apple India',
    description: 'Supercharged by the M2 chip for next-level performance. Incredibly thin and light, with up to 18 hours of battery life.',
    highlights: ['M2 chip performance', '18-hour battery', 'Liquid Retina display', 'MagSafe 3', 'Silent fanless design'],
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '4',
    name: 'Nike Air Zoom Pegasus 40 Running Shoes',
    brand: 'Nike',
    category: 'Fashion',
    price: 6499,
    comparePrice: 9995,
    rating: 4.7,
    reviews: 3204,
    stock: 89,
    vendor: 'Nike Store',
    description: 'Responsive cushioning for your daily miles. The Pegasus 40 delivers a smooth ride with a lightweight feel.',
    highlights: ['Responsive Zoom Air', 'Breathable mesh', 'Durable rubber outsole', 'Lightweight design', 'Versatile running shoe'],
    image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '5',
    name: 'The Ordinary Skincare Set - Niacinamide + Hyaluronic Bundle',
    brand: 'The Ordinary',
    category: 'Beauty',
    price: 1299,
    comparePrice: 2100,
    rating: 4.5,
    reviews: 981,
    stock: 156,
    vendor: 'Beauty Hub',
    description: 'A complete skincare routine featuring Niacinamide 10% + Zinc 1% and Hyaluronic Acid 2% + B5 for deep hydration.',
    highlights: ['Reduces blemishes', 'Deep hydration', 'Dermatologist tested', 'Cruelty-free', 'Vegan friendly'],
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '6',
    name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker 5.7L',
    brand: 'Instant Pot',
    category: 'Home & Kitchen',
    price: 5499,
    comparePrice: 10999,
    rating: 4.6,
    reviews: 4562,
    stock: 67,
    vendor: 'Kitchen World',
    description: '7 appliances in 1: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.',
    highlights: ['7-in-1 functionality', '14 smart programs', '5.7L large capacity', 'Stainless steel inner pot', 'Quick one-touch cooking'],
    image: 'https://images.unsplash.com/photo-1586159270355-05036a7a1f3e?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '7',
    name: 'Adidas Ultraboost 22 Running Shoes',
    brand: 'Adidas',
    category: 'Fashion',
    price: 8999,
    comparePrice: 14999,
    rating: 4.6,
    reviews: 2341,
    stock: 45,
    vendor: 'Adidas Store',
    description: 'Designed for runners who want an energized ride. Featuring BoostX midsole for maximum energy return.',
    highlights: ['BoostX energy return', 'Primeknit+ adaptive fit', 'Continental rubber outsole', 'Lightweight construction', 'Responsive cushioning'],
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '8',
    name: 'Canon EOS R50 Mirrorless Camera 24.2MP',
    brand: 'Canon',
    category: 'Electronics',
    price: 49990,
    comparePrice: 64990,
    rating: 4.7,
    reviews: 892,
    stock: 18,
    vendor: 'Camera Pro',
    description: 'The smallest and lightest EOS R camera yet. Features 4K video recording and advanced autofocus.',
    highlights: ['24.2MP APS-C sensor', '4K UHD video', 'Smart subject tracking', 'Creative assist modes', 'Compact lightweight body'],
    image: 'https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '9',
    name: 'MAC Studio Fix Powder Plus Foundation',
    brand: 'MAC',
    category: 'Beauty',
    price: 1850,
    comparePrice: 2200,
    rating: 4.4,
    reviews: 12043,
    stock: 234,
    vendor: 'Beauty Hub',
    description: 'A buildable, medium-to-full coverage foundation with a natural matte finish. Contains vitamins A and E.',
    highlights: ['Buildable coverage', '12-hour wear', 'Matte finish', 'Vitamin-enriched', 'Non-comedogenic'],
    image: 'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '10',
    name: 'Philips Hue Smart LED Bulb Starter Kit',
    brand: 'Philips',
    category: 'Home & Kitchen',
    price: 3499,
    comparePrice: 4499,
    rating: 4.3,
    reviews: 1567,
    stock: 78,
    vendor: 'Smart Home',
    description: 'Transform your home with smart lighting. Control up to 10 lights with the Hue Bridge.',
    highlights: ['16 million colors', 'Voice control compatible', 'Energy efficient LED', 'Easy setup', 'Scheduling & automation'],
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '11',
    name: 'Atomic Habits by James Clear - Paperback',
    brand: 'Avery',
    category: 'Books',
    price: 299,
    comparePrice: 499,
    rating: 4.9,
    reviews: 84231,
    stock: 500,
    vendor: 'Book Palace',
    description: 'An easy & proven way to build good habits & break bad ones. Tiny changes, remarkable results.',
    highlights: ['Bestselling self-help', 'Practical framework', 'Easy to implement', 'Life-changing strategies', 'Over 84K reviews'],
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '12',
    name: 'Samsung 65 inch 4K QLED Smart TV',
    brand: 'Samsung',
    category: 'Electronics',
    price: 74990,
    comparePrice: 119900,
    rating: 4.6,
    reviews: 3421,
    stock: 8,
    vendor: 'Samsung India',
    description: 'Quantum HDR 4X for stunning detail. Neural Quantum Processor 4K for upscaling.',
    highlights: ['QLED 4K display', 'Neural Quantum Processor', 'Motion Xcelerator', 'Gaming Hub', 'Smart TV platform'],
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '13',
    name: 'boAt Airdopes 441 Bluetooth Truly Wireless Earbuds',
    brand: 'boAt',
    category: 'Electronics',
    price: 1499,
    comparePrice: 3990,
    rating: 4.4,
    reviews: 41290,
    stock: 220,
    vendor: 'boAt Official',
    description: 'Truly wireless earbuds with 42HRS total playback. ASAP Charge - 10 min charge for 120 min playback.',
    highlights: ['42HRS total playback', 'ASAP charge', 'IWP technology', 'ENx call clarity', 'Bluetooth 5.3'],
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '14',
    name: 'Samsung Galaxy S24 5G (256GB) - Phantom Black',
    brand: 'Samsung',
    category: 'Electronics',
    price: 79999,
    comparePrice: 89999,
    rating: 4.7,
    reviews: 9843,
    stock: 16,
    vendor: 'Samsung India',
    description: 'Galaxy AI is here. Snapdragon 8 Gen 3 processor. 50MP pro-grade camera system.',
    highlights: ['Galaxy AI features', 'Snapdragon 8 Gen 3', '50MP camera system', '256GB storage', '5000mAh battery'],
    image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '15',
    name: 'Dell 24-inch IPS Full HD Monitor (UltraSharp)',
    brand: 'Dell',
    category: 'Electronics',
    price: 15999,
    comparePrice: 24999,
    rating: 4.5,
    reviews: 6211,
    stock: 34,
    vendor: 'Dell Store',
    description: '23.8-inch Full HD 1920x1080 IPS display with 99% sRGB color coverage.',
    highlights: ['IPS display', '99% sRGB coverage', 'Narrow bezel', 'Tilt adjustable', 'Eye-safe comfort'],
    image: 'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '16',
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    brand: 'JBL',
    category: 'Electronics',
    price: 8999,
    comparePrice: 11999,
    rating: 4.6,
    reviews: 9320,
    stock: 64,
    vendor: 'JBL India',
    description: 'Powerful sound in a compact design. IPX7 waterproof. Up to 12 hours of playtime.',
    highlights: ['IPX7 waterproof', '12-hour battery', 'PartyBoost feature', 'Rich bass sound', 'Portable design'],
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '17',
    name: "Levi's Men's 511 Slim Fit Jeans",
    brand: "Levi's",
    category: 'Fashion',
    price: 2499,
    comparePrice: 3999,
    rating: 4.3,
    reviews: 1203,
    stock: 128,
    vendor: "Levi's Store",
    description: 'The 511 Slim is the perfect balance between classic straight and skinny. Made with stretch for comfort.',
    highlights: ['Slim fit design', 'Stretch fabric', "Classic Levi's quality", 'Below waist fit', 'Machine washable'],
    image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '18',
    name: "H&M Women's Oversized Hoodie",
    brand: 'H&M',
    category: 'Fashion',
    price: 1799,
    comparePrice: 2499,
    rating: 4.2,
    reviews: 880,
    stock: 98,
    vendor: 'H&M Official',
    description: 'Relaxed oversized hoodie in soft organic cotton jersey with drawstring hood and kangaroo pocket.',
    highlights: ['Oversized fit', 'Organic cotton', 'Drawstring hood', 'Kangaroo pocket', 'Ribbed trims'],
    image: 'https://images.unsplash.com/photo-1520975958225-3f61d721a6b0?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '19',
    name: 'Puma Unisex Backpack 28L',
    brand: 'Puma',
    category: 'Fashion',
    price: 1599,
    comparePrice: 2499,
    rating: 4.4,
    reviews: 3422,
    stock: 140,
    vendor: 'Puma Store',
    description: '28-liter backpack perfect for daily use with laptop sleeve and padded shoulder straps.',
    highlights: ['28L capacity', 'Laptop sleeve', 'Water bottle pockets', 'Padded straps', 'Durable material'],
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '20',
    name: 'IKEA LACK Coffee Table',
    brand: 'IKEA',
    category: 'Home & Kitchen',
    price: 1299,
    comparePrice: 1999,
    rating: 4.4,
    reviews: 5401,
    stock: 40,
    vendor: 'IKEA India',
    description: 'Simple and modern coffee table. Lightweight and easy to move with clean lines.',
    highlights: ['Modern design', 'Easy to assemble', 'Lightweight', 'Easy to clean', 'Space-saving'],
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '21',
    name: 'PlayStation 5 Console (Disc Edition)',
    brand: 'Sony',
    category: 'Gaming',
    price: 49990,
    comparePrice: 54990,
    rating: 4.9,
    reviews: 12450,
    stock: 5,
    vendor: 'Sony India',
    description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
    highlights: ['Ultra-high speed SSD', 'Haptic feedback', 'Adaptive triggers', '4K-TV gaming', '3D Audio technology'],
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '22',
    name: 'Nintendo Switch OLED Model - White',
    brand: 'Nintendo',
    category: 'Gaming',
    price: 32990,
    comparePrice: 35990,
    rating: 4.8,
    reviews: 8740,
    stock: 15,
    vendor: 'Gaming World',
    description: 'Meet the newest member of the Nintendo Switch family. The new system features a vibrant 7-inch OLED screen, a wide adjustable stand, and wired LAN port.',
    highlights: ['7-inch OLED screen', 'Wide adjustable stand', '64 GB internal storage', 'Enhanced audio', 'Wired LAN port'],
    image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop&auto=format',
  },
  {
    _id: '23',
    name: 'Sony DualSense Wireless Controller',
    brand: 'Sony',
    category: 'Gaming',
    price: 5990,
    comparePrice: 6390,
    rating: 4.7,
    reviews: 25600,
    stock: 40,
    vendor: 'Sony India',
    description: 'Discover a deeper, highly immersive gaming experience with the innovative new PS5 controller, featuring haptic feedback and dynamic trigger effects.',
    highlights: ['Haptic feedback', 'Adaptive triggers', 'Built-in microphone', 'Create button', 'Signature comfort'],
    image: 'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=400&h=400&fit=crop&auto=format',
  },
];

// For demo: assign all products to a single vendor so orders are always assigned
export const DEFAULT_VENDOR = 'Demo Vendor';
PRODUCTS.forEach((p) => {
  p.vendor = DEFAULT_VENDOR;
});

// ─── VENDORS ─────────────────────────────────────────────────────

export const VENDORS = [
  { storeName: 'Sony India', owner: 'Akira Tanaka', email: 'vendor@sony.in', status: 'approved', revenue: 2450000, productsCount: 12 },
  { storeName: 'Apple India', owner: 'Sarah Williams', email: 'seller@apple.in', status: 'approved', revenue: 1890000, productsCount: 8 },
  { storeName: 'Beauty Hub', owner: 'Priya Sharma', email: 'admin@beautyhub.in', status: 'pending', revenue: 0, productsCount: 0 },
  { storeName: 'Kitchen World', owner: 'Rahul Verma', email: 'info@kitchenworld.in', status: 'approved', revenue: 456000, productsCount: 15 },
  { storeName: 'Nike Store', owner: 'Marcus Johnson', email: 'seller@nike.in', status: 'approved', revenue: 890000, productsCount: 10 },
  { storeName: 'Book Palace', owner: 'Anjali Singh', email: 'books@bookpalace.in', status: 'rejected', revenue: 0, productsCount: 0 },
  { storeName: 'Smart Home', owner: 'David Chen', email: 'contact@smarthome.in', status: 'pending', revenue: 0, productsCount: 0 },
  { storeName: 'Adidas Store', owner: 'Emma Rodriguez', email: 'seller@adidas.in', status: 'approved', revenue: 623000, productsCount: 9 },
  { storeName: 'Demo Vendor', owner: 'You', email: 'demo@vendor.local', status: 'approved', revenue: 0, productsCount: 0 },
];

// ─── ORDERS ──────────────────────────────────────────────────────

export const ORDERS = [
  {
    _id: 'ord1',
    orderId: 'ORD-1001',
    orderNumber: 'ORD-1001',
    customer: 'Priya Sharma',
    products: [
      { _id: '1', name: 'Sony WH-1000XM5', price: 18990, quantity: 1 },
      { _id: '5', name: 'The Ordinary Skincare Set', price: 1299, quantity: 2 },
    ],
    total: 21588,
    status: 'delivered',
    date: '2024-01-15',
    address: '12 MG Road, Delhi 110001',
  },
  {
    orderId: 'ORD-1002',
    customer: 'Rahul Verma',
    products: [{ _id: '3', name: 'MacBook Air M2', price: 89990, quantity: 1 }],
    total: 89990,
    status: 'shipped',
    date: '2024-01-20',
    address: '45 FC Road, Pune 411001',
  },
  {
    orderId: 'ORD-1003',
    customer: 'Anjali Singh',
    products: [
      { _id: '4', name: 'Nike Air Zoom Pegasus 40', price: 6499, quantity: 1 },
      { _id: '7', name: 'Adidas Ultraboost 22', price: 8999, quantity: 1 },
    ],
    total: 15498,
    status: 'processing',
    date: '2024-01-22',
    address: '7 Linking Road, Mumbai 400050',
  },
  {
    orderId: 'ORD-1004',
    customer: 'Vikram Patel',
    products: [{ _id: '6', name: 'Instant Pot Duo 7-in-1', price: 5499, quantity: 1 }],
    total: 5499,
    status: 'pending',
    date: '2024-01-23',
    address: '23 JP Nagar, Bangalore 560078',
  },
  {
    orderId: 'ORD-1005',
    customer: 'Sneha Rao',
    products: [{ _id: '9', name: 'MAC Studio Fix Foundation', price: 1850, quantity: 2 }],
    total: 3700,
    status: 'delivered',
    date: '2024-01-14',
    address: '18 Indiranagar, Bangalore 560038',
  },
  {
    orderId: 'ORD-1006',
    customer: 'Amit Kumar',
    products: [{ _id: '12', name: 'Samsung 65" QLED TV', price: 74990, quantity: 1 }],
    total: 74990,
    status: 'shipped',
    date: '2024-01-25',
    address: 'Sector 15, Chandigarh 160015',
  },
  {
    orderId: 'ORD-1007',
    customer: 'Meera Nair',
    products: [
      { _id: '13', name: 'boAt Airdopes 441', price: 1499, quantity: 1 },
      { _id: '16', name: 'JBL Flip 6 Speaker', price: 8999, quantity: 1 },
    ],
    total: 10498,
    status: 'delivered',
    date: '2024-01-18',
    address: 'Fort Kochi, Kochi 682001',
  },
  {
    orderId: 'ORD-1008',
    customer: 'Arjun Reddy',
    products: [{ _id: '14', name: 'Samsung Galaxy S24', price: 79999, quantity: 1 }],
    total: 79999,
    status: 'processing',
    date: '2024-01-26',
    address: 'Banjara Hills, Hyderabad 500034',
  },
  {
    orderId: 'ORD-1009',
    customer: 'Kavya Iyer',
    products: [{ _id: '11', name: 'Atomic Habits', price: 299, quantity: 3 }],
    total: 897,
    status: 'delivered',
    date: '2024-01-12',
    address: 'Anna Nagar, Chennai 600040',
  },
  {
    orderId: 'ORD-1010',
    customer: 'Rohan Mehta',
    products: [{ _id: '15', name: 'Dell 24" Monitor', price: 15999, quantity: 2 }],
    total: 31998,
    status: 'shipped',
    date: '2024-01-24',
    address: 'Ghatkopar West, Mumbai 400086',
  },
  {
    orderId: 'ORD-1011',
    customer: 'Deepa Nair',
    products: [
      { _id: '17', name: "Levi's 511 Jeans", price: 2499, quantity: 2 },
      { _id: '18', name: 'H&M Oversized Hoodie', price: 1799, quantity: 1 },
    ],
    total: 6797,
    status: 'delivered',
    date: '2024-01-16',
    address: 'Koramangala, Bangalore 560095',
  },
  {
    orderId: 'ORD-1012',
    customer: 'Vishal Agarwal',
    products: [{ _id: '20', name: 'IKEA LACK Coffee Table', price: 1299, quantity: 1 }],
    total: 1299,
    status: 'cancelled',
    date: '2024-01-10',
    address: 'Vasant Vihar, Delhi 110057',
  },
  {
    orderId: 'ORD-1013',
    customer: 'Nisha Gupta',
    products: [{ _id: '5', name: 'The Ordinary Skincare Set', price: 1299, quantity: 2 }],
    total: 2598,
    status: 'delivered',
    date: '2024-01-19',
    address: 'Salt Lake, Kolkata 700091',
  },
  {
    orderId: 'ORD-1014',
    customer: 'Karan Singh',
    products: [{ _id: '4', name: 'Nike Air Zoom Pegasus 40', price: 6499, quantity: 1 }],
    total: 6499,
    status: 'processing',
    date: '2024-01-27',
    address: 'Sector 22, Chandigarh 160022',
  },
  {
    orderId: 'ORD-1015',
    customer: 'Tanya Kapoor',
    products: [
      { _id: '13', name: 'boAt Airdopes 441', price: 1499, quantity: 1 },
      { _id: '16', name: 'JBL Flip 6 Speaker', price: 8999, quantity: 1 },
    ],
    total: 10498,
    status: 'shipped',
    date: '2024-01-28',
    address: 'Andheri West, Mumbai 400058',
  },
];

// ─── VENDOR DUMMY DATA ───────────────────────────────────────────

export const VENDOR_PRODUCTS = [
  {
    _id: 'vp1',
    name: 'Sony WH-1000XM5 Wireless Headphones',
    category: 'Electronics',
    price: 18990,
    comparePrice: 32990,
    stock: 45,
    status: 'active',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=80&h=80&fit=crop',
  totalSold: 128,
  sold: 128,
  vendor: 'Demo Vendor',
  },
  {
    _id: 'vp2',
    name: 'Apple Watch Series 9 GPS 41mm',
    category: 'Electronics',
    price: 34900,
    comparePrice: 41900,
    stock: 23,
    status: 'active',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=80&h=80&fit=crop',
  totalSold: 89,
  sold: 89,
  vendor: 'Demo Vendor',
  },
  {
    _id: 'vp3',
    name: 'JBL Flip 6 Portable Bluetooth Speaker',
    category: 'Electronics',
    price: 8999,
    comparePrice: 11999,
    stock: 3,
    status: 'active',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=80&h=80&fit=crop',
  totalSold: 210,
  sold: 210,
  vendor: 'Demo Vendor',
  },
  {
    _id: 'vp4',
    name: 'boAt Airdopes 441 TWS Earbuds',
    category: 'Electronics',
    price: 1499,
    comparePrice: 3990,
    stock: 0,
    status: 'inactive',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=80&h=80&fit=crop',
  totalSold: 543,
  sold: 543,
  vendor: 'Demo Vendor',
  },
  {
    _id: 'vp5',
    name: 'Samsung 65" 4K QLED Smart TV',
    category: 'Electronics',
    price: 74990,
    comparePrice: 119900,
    stock: 8,
    status: 'active',
    image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=80&h=80&fit=crop',
  totalSold: 34,
  sold: 34,
  vendor: 'Demo Vendor',
  },
];

export const VENDOR_ORDERS = [
  {
    orderId: 'ORD-1001',
    customer: 'Priya Sharma',
    customerEmail: 'priya@email.com',
    product: 'Sony WH-1000XM5',
    productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=60&h=60&fit=crop',
    qty: 1,
    amount: 18990,
  date: '2024-01-15',
  status: 'delivered',
  vendor: 'Demo Vendor',
    address: '12 MG Road, Delhi 110001',
  },
  {
    orderId: 'ORD-1002',
    customer: 'Rahul Verma',
    customerEmail: 'rahul@email.com',
    product: 'Apple Watch Series 9',
    productImage: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=60&h=60&fit=crop',
    qty: 1,
    amount: 34900,
  date: '2024-01-20',
  status: 'shipped',
  vendor: 'Demo Vendor',
    address: '45 FC Road, Pune 411001',
  },
  {
    orderId: 'ORD-1003',
    customer: 'Anjali Singh',
    customerEmail: 'anjali@email.com',
    product: 'JBL Flip 6 Speaker',
    productImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=60&h=60&fit=crop',
    qty: 2,
    amount: 17998,
  date: '2024-01-22',
  status: 'processing',
  vendor: 'Demo Vendor',
    address: '7 Linking Road, Mumbai 400050',
  },
  {
    orderId: 'ORD-1004',
    customer: 'Vikram Patel',
    customerEmail: 'vikram@email.com',
    product: 'boAt Airdopes 441',
    productImage: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=60&h=60&fit=crop',
    qty: 1,
    amount: 1499,
  date: '2024-01-23',
  status: 'pending',
  vendor: 'Demo Vendor',
    address: '23 JP Nagar, Bangalore 560078',
  },
  {
    orderId: 'ORD-1005',
    customer: 'Sneha Rao',
    customerEmail: 'sneha@email.com',
    product: 'Samsung 65" QLED TV',
    productImage: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=60&h=60&fit=crop',
    qty: 1,
    amount: 74990,
  date: '2024-01-24',
  status: 'delivered',
  vendor: 'Demo Vendor',
    address: '18 Indiranagar, Bangalore 560038',
  },
  {
    orderId: 'ORD-1006',
    customer: 'Amit Kumar',
    customerEmail: 'amit@email.com',
    product: 'Sony WH-1000XM5',
    productImage: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=60&h=60&fit=crop',
    qty: 1,
    amount: 18990,
  date: '2024-01-25',
  status: 'cancelled',
  vendor: 'Demo Vendor',
    address: 'Sector 15, Chandigarh 160015',
  },
  {
    orderId: 'ORD-1007',
    customer: 'Meera Nair',
    customerEmail: 'meera@email.com',
    product: 'JBL Flip 6 Speaker',
    productImage: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=60&h=60&fit=crop',
    qty: 1,
    amount: 8999,
  date: '2024-01-26',
  status: 'shipped',
  vendor: 'Demo Vendor',
    address: 'Fort Kochi, Kochi 682001',
  },
];

// ─── ADMIN DUMMY DATA ────────────────────────────────────────────

export const ADMIN_VENDORS = [
  { _id: 'av1', storeName: 'Sony India', owner: 'Akira Tanaka', email: 'vendor@sony.in', gst: '27AADCS1681R1ZS', status: 'approved', productsCount: 12, revenue: 2450000, joinedDate: '2023-06-15' },
  { _id: 'av2', storeName: 'Apple India', owner: 'Sarah Williams', email: 'seller@apple.in', gst: '27AAICA6456R1ZQ', status: 'approved', productsCount: 8, revenue: 1890000, joinedDate: '2023-07-20' },
  { _id: 'av3', storeName: 'Beauty Hub', owner: 'Priya Sharma', email: 'admin@beautyhub.in', gst: '07AABCB1234M1Z5', status: 'pending', productsCount: 0, revenue: 0, joinedDate: '2024-01-22' },
  { _id: 'av4', storeName: 'Kitchen World', owner: 'Rahul Verma', email: 'info@kitchenworld.in', gst: '29AABCK9876R1Z1', status: 'approved', productsCount: 15, revenue: 456000, joinedDate: '2023-09-10' },
  { _id: 'av5', storeName: 'Nike Store', owner: 'Marcus Johnson', email: 'seller@nike.in', gst: '27AADCN4512R1ZA', status: 'approved', productsCount: 10, revenue: 890000, joinedDate: '2023-08-05' },
  { _id: 'av6', storeName: 'Book Palace', owner: 'Anjali Singh', email: 'books@bookpalace.in', gst: '33AABCB5678R1ZB', status: 'rejected', productsCount: 0, revenue: 0, joinedDate: '2024-01-10' },
  { _id: 'av7', storeName: 'Smart Home', owner: 'David Chen', email: 'contact@smarthome.in', gst: '29AABCS1357R1ZC', status: 'pending', productsCount: 0, revenue: 0, joinedDate: '2024-01-25' },
  { _id: 'av8', storeName: 'Adidas Store', owner: 'Emma Rodriguez', email: 'seller@adidas.in', gst: '27AADCA2468R1ZD', status: 'approved', productsCount: 9, revenue: 623000, joinedDate: '2023-10-18' },
  { _id: 'av9', storeName: 'Demo Vendor', owner: 'You', email: 'demo@vendor.local', gst: '07DEMOVEN1234X1', status: 'approved', productsCount: 5, revenue: 0, joinedDate: '2024-05-01' },
];

// ─── ADMIN USERS (dummy) ───────────────────────────────────────
export const ADMIN_USERS = [
  {
    _id: 'admin1',
    name: 'Site Admin',
    email: 'admin@shopzone.local',
    role: 'admin',
    joinedDate: '2023-05-01',
    bio: 'Primary administrative user for demo and testing.'
  }
];

export const ADMIN_ORDERS = [
  { orderId: 'ORD-1001', customer: 'Priya Sharma', vendor: 'Sony India', amount: 21588, items: 2, date: '2024-01-15', status: 'delivered', warehouse: 'Delhi Hub' },
  { orderId: 'ORD-1002', customer: 'Rahul Verma', vendor: 'Apple India', amount: 89990, items: 1, date: '2024-01-20', status: 'shipped', warehouse: 'Pune Hub' },
  { orderId: 'ORD-1003', customer: 'Anjali Singh', vendor: 'Nike Store', amount: 15498, items: 2, date: '2024-01-22', status: 'processing', warehouse: null },
  { orderId: 'ORD-1004', customer: 'Vikram Patel', vendor: 'Kitchen World', amount: 5499, items: 1, date: '2024-01-23', status: 'pending', warehouse: null },
  { orderId: 'ORD-1005', customer: 'Sneha Rao', vendor: 'Beauty Hub', amount: 4199, items: 2, date: '2024-01-14', status: 'delivered', warehouse: 'Bangalore Hub' },
  { orderId: 'ORD-1006', customer: 'Amit Kumar', vendor: 'Samsung India', amount: 74990, items: 1, date: '2024-01-25', status: 'shipped', warehouse: 'Chandigarh Hub' },
  { orderId: 'ORD-1007', customer: 'Meera Nair', vendor: 'Sony India', amount: 10498, items: 2, date: '2024-01-18', status: 'delivered', warehouse: 'Kochi Hub' },
  { orderId: 'ORD-1008', customer: 'Arjun Reddy', vendor: 'Samsung India', amount: 79999, items: 1, date: '2024-01-26', status: 'processing', warehouse: null },
  { orderId: 'ORD-1009', customer: 'Kavya Iyer', vendor: 'Book Palace', amount: 1415, items: 3, date: '2024-01-12', status: 'delivered', warehouse: 'Chennai Hub' },
  { orderId: 'ORD-1010', customer: 'Rohan Mehta', vendor: 'Dell Store', amount: 31998, items: 2, date: '2024-01-24', status: 'shipped', warehouse: 'Mumbai Hub' },
];

// ─── WAREHOUSE DUMMY DATA ────────────────────────────────────────

export const WAREHOUSE_SHIPMENTS = [
  {
    _id: 'ws1',
    orderId: 'ORD-1001',
    customer: 'Priya Sharma',
    customerAddress: '12 MG Road, Delhi 110001',
    customerPhone: '+91 98765 43210',
    products: [
      { name: 'Sony WH-1000XM5', qty: 1, image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=60&h=60&fit=crop' },
      { name: 'The Ordinary Skincare Set', qty: 2, image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=60&h=60&fit=crop' },
    ],
    vendor: 'Sony India',
    assignedDate: '2024-01-15',
    status: 'delivered',
    trackingId: 'TRK-DEL-001234',
    courier: 'Delhivery',
    updatedAt: '2024-01-18',
  },
  {
    _id: 'ws2',
    orderId: 'ORD-1002',
    customer: 'Rahul Verma',
    customerAddress: '45 FC Road, Pune 411001',
    customerPhone: '+91 87654 32109',
    products: [
      { name: 'Apple MacBook Air M2', qty: 1, image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=60&h=60&fit=crop' },
    ],
    vendor: 'Apple India',
    assignedDate: '2024-01-20',
    status: 'dispatched',
    trackingId: 'TRK-PUN-005678',
    courier: 'Bluedart',
    updatedAt: '2024-01-22',
  },
  {
    _id: 'ws3',
    orderId: 'ORD-1003',
    customer: 'Anjali Singh',
    customerAddress: '7 Linking Road, Mumbai 400050',
    customerPhone: '+91 76543 21098',
    products: [
      { name: 'Nike Air Zoom Pegasus 40', qty: 1, image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=60&h=60&fit=crop' },
      { name: 'Adidas Ultraboost 22', qty: 1, image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?w=60&h=60&fit=crop' },
    ],
    vendor: 'Nike Store',
    assignedDate: '2024-01-22',
    status: 'packed',
    trackingId: '',
    courier: '',
    updatedAt: '2024-01-23',
  },
  {
    _id: 'ws4',
    orderId: 'ORD-1004',
    customer: 'Vikram Patel',
    customerAddress: '23 JP Nagar, Bangalore 560078',
    customerPhone: '+91 65432 10987',
    products: [
      { name: 'Instant Pot Duo 7-in-1', qty: 1, image: 'https://images.unsplash.com/photo-1586159270355-05036a7a1f3e?w=60&h=60&fit=crop' },
    ],
    vendor: 'Kitchen World',
    assignedDate: '2024-01-23',
    status: 'received',
    trackingId: '',
    courier: '',
    updatedAt: '2024-01-23',
  },
  {
    _id: 'ws5',
    orderId: 'ORD-1006',
    customer: 'Amit Kumar',
    customerAddress: 'Sector 15, Chandigarh 160015',
    customerPhone: '+91 54321 09876',
    products: [
      { name: 'Samsung 65" QLED TV', qty: 1, image: 'https://images.unsplash.com/photo-1593784991095-a205069470b6?w=60&h=60&fit=crop' },
    ],
    vendor: 'Samsung India',
    assignedDate: '2024-01-25',
    status: 'dispatched',
    trackingId: 'TRK-CHD-009012',
    courier: 'DTDC',
    updatedAt: '2024-01-26',
  },
  {
    _id: 'ws6',
    orderId: 'ORD-1008',
    customer: 'Arjun Reddy',
    customerAddress: 'Banjara Hills, Hyderabad 500034',
    customerPhone: '+91 43210 98765',
    products: [
      { name: 'Samsung Galaxy S24', qty: 1, image: 'https://images.unsplash.com/photo-1510557880182-3d4d3cba35a5?w=60&h=60&fit=crop' },
    ],
    vendor: 'Samsung India',
    assignedDate: '2024-01-26',
    status: 'received',
    trackingId: '',
    courier: '',
    updatedAt: '2024-01-26',
  },
  {
    _id: 'ws7',
    orderId: 'ORD-1010',
    customer: 'Rohan Mehta',
    customerAddress: 'Ghatkopar West, Mumbai 400086',
    customerPhone: '+91 32109 87654',
    products: [
      { name: 'Dell 24" Monitor', qty: 2, image: 'https://images.unsplash.com/photo-1527443154391-507e9dc6c5cc?w=60&h=60&fit=crop' },
    ],
    vendor: 'Dell Store',
    assignedDate: '2024-01-24',
    status: 'out_for_delivery',
    trackingId: 'TRK-MUM-003456',
    courier: 'Ekart',
    updatedAt: '2024-01-27',
  },
  {
    _id: 'ws8',
    orderId: 'ORD-1015',
    customer: 'Tanya Kapoor',
    customerAddress: 'Andheri West, Mumbai 400058',
    customerPhone: '+91 21098 76543',
    products: [
      { name: 'LEGO Classic Bricks', qty: 1, image: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=60&h=60&fit=crop' },
      { name: 'Sony DualSense Controller', qty: 1, image: 'https://images.unsplash.com/photo-1593118247619-e2d6f056869e?w=60&h=60&fit=crop' },
    ],
    vendor: 'Sony India',
    assignedDate: '2024-01-28',
    status: 'packed',
    trackingId: '',
    courier: '',
    updatedAt: '2024-01-28',
  },
];